bot:
  version_updates:
    exclude:
    - '20250505181427'
build_platform:
  linux_aarch64: linux_64
  osx_arm64: osx_64
channel_priority: strict
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
github_actions:
  resize_win_partitions: true
  self_hosted: true
  timeout_minutes: 720
  triggers:
  - push
  - pull_request
provider:
  win_64: github_actions
test: native_and_emulated
