bot:
  version_updates:
    exclude:
    - '20250505181427'
channel_priority: strict
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
workflow_settings:
  resize_partitions:
    - provider: github_actions
      os: win
      value: true  
github_actions:
  timeout_minutes: 720
provider:
  linux_aarch64: default
  osx_arm64: default
  win_64: github_actions
test: native_and_emulated
