channel_priority: strict
azure:
  store_build_artifacts: True
  settings_win:
    pool:
      vmImage: windows-2019
build_platform:
  osx_arm64: osx_64
  linux_aarch64: linux_64
provider:
  win_64: appveyor
os_version:
  linux_64: cos7
test: native_and_emulated
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
